export const CHECKOUT_BOOKING = 'CHECKOUT_BOOKING';
export const CHECKOUT_STATE = 'CHECKOUT_STATE';
export const RATE_BOOKING = 'RATE_BOOKING';
export const FETCH_PAGE = 'FETCH_PAGE';
export const INIT_PAGE = 'INIT_PAGE';
