const {getObjectId, getObjectIds} = require('mongo-seeding');

module.exports = [
    {
        id: getObjectId('role-view'),
        permission: 'role-view',
        module: 'master',
        submodule: 'role',
        description: 'View role data',
    },
    {
        id: getObjectId('role-create'),
        permission: 'role-create',
        module: 'master',
        submodule: 'role',
        description: 'Create role data',
    },
    {
        id: getObjectId('role-edit'),
        permission: 'role-edit',
        module: 'master',
        submodule: 'role',
        description: 'Edit role data',
    },
    {
        id: getObjectId('role-delete'),
        permission: 'role-delete',
        module: 'master',
        submodule: 'role',
        description: 'Delete role data',
    },

    {
        id: getObjectId('user-view'),
        permission: 'user-view',
        module: 'master',
        submodule: 'user',
        description: 'View user data',
    },
    {
        id: getObjectId('user-create'),
        permission: 'user-create',
        module: 'master',
        submodule: 'user',
        description: 'Create user data',
    },
    {
        id: getObjectId('user-edit'),
        permission: 'user-edit',
        module: 'master',
        submodule: 'user',
        description: 'Edit user data',
    },
    {
        id: getObjectId('user-delete'),
        permission: 'user-delete',
        module: 'master',
        submodule: 'user',
        description: 'Delete user data',
    },

    {
        id: getObjectId('bank-view'),
        permission: 'bank-view',
        module: 'master',
        submodule: 'bank',
        description: 'View bank data',
    },
    {
        id: getObjectId('bank-create'),
        permission: 'bank-create',
        module: 'master',
        submodule: 'bank',
        description: 'Create bank data',
    },
    {
        id: getObjectId('bank-edit'),
        permission: 'bank-edit',
        module: 'master',
        submodule: 'bank',
        description: 'Edit bank data',
    },
    {
        id: getObjectId('bank-delete'),
        permission: 'bank-delete',
        module: 'master',
        submodule: 'bank',
        description: 'Delete bank data',
    },

    {
        id: getObjectId('facility-view'),
        permission: 'facility-view',
        module: 'master',
        submodule: 'facility',
        description: 'View facility data',
    },
    {
        id: getObjectId('facility-create'),
        permission: 'facility-create',
        module: 'master',
        submodule: 'facility',
        description: 'Create facility data',
    },
    {
        id: getObjectId('facility-edit'),
        permission: 'facility-edit',
        module: 'master',
        submodule: 'facility',
        description: 'Edit facility data',
    },
    {
        id: getObjectId('facility-delete'),
        permission: 'facility-delete',
        module: 'master',
        submodule: 'facility',
        description: 'Delete facility data',
    },

    {
        id: getObjectId('category-view'),
        permission: 'category-view',
        module: 'master',
        submodule: 'category',
        description: 'View category data',
    },
    {
        id: getObjectId('category-create'),
        permission: 'category-create',
        module: 'master',
        submodule: 'category',
        description: 'Create category data',
    },
    {
        id: getObjectId('category-edit'),
        permission: 'category-edit',
        module: 'master',
        submodule: 'category',
        description: 'Edit category data',
    },
    {
        id: getObjectId('category-delete'),
        permission: 'category-delete',
        module: 'master',
        submodule: 'category',
        description: 'Delete category data',
    },

    {
        id: getObjectId('item-view'),
        permission: 'item-view',
        module: 'transaction',
        submodule: 'item',
        description: 'View item data',
    },
    {
        id: getObjectId('item-create'),
        permission: 'item-create',
        module: 'transaction',
        submodule: 'item',
        description: 'Create item data',
    },
    {
        id: getObjectId('item-edit'),
        permission: 'item-edit',
        module: 'transaction',
        submodule: 'item',
        description: 'Edit item data',
    },
    {
        id: getObjectId('item-delete'),
        permission: 'item-delete',
        module: 'transaction',
        submodule: 'item',
        description: 'Delete item data',
    },

    {
        id: getObjectId('booking-view'),
        permission: 'booking-view',
        module: 'transaction',
        submodule: 'booking',
        description: 'View booking data',
    },
    {
        id: getObjectId('booking-create'),
        permission: 'booking-create',
        module: 'transaction',
        submodule: 'booking',
        description: 'Create booking data',
    },
    {
        id: getObjectId('booking-edit'),
        permission: 'booking-edit',
        module: 'transaction',
        submodule: 'booking',
        description: 'Edit booking data',
    },
    {
        id: getObjectId('booking-delete'),
        permission: 'booking-delete',
        module: 'transaction',
        submodule: 'booking',
        description: 'Delete booking data',
    },

    {
        id: getObjectId('account-edit'),
        permission: 'account-edit',
        module: 'utility',
        submodule: 'account',
        description: 'Edit account data',
    },
    {
        id: getObjectId('setting-edit'),
        permission: 'setting-edit',
        module: 'utility',
        submodule: 'setting',
        description: 'Edit setting data',
    },
    {
        id: getObjectId('log-view'),
        permission: 'log-view',
        module: 'utility',
        submodule: 'log',
        description: 'View activity log data',
    },
];